apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
namespace: instavote
images:
  - name: schoolofdevops/vote
    newName: kzwolenik95/vote
    newTag: main-59f9b466-1732975561 #{"$imagepolicy": "flux-system:vote:tag"}
replicas:
  - name: vote
    count: 4
configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=STAGING
      - OPTION_B=DEV
