apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
namespace: instavote
images:
  - name: schoolofdevops/vote
    newTag: v6
replicas:
  - name: vote
    count: 4
configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=STAGING
      - OPTION_B=DEV
